### ISSUE TITLE
schedule link is missing base URL 

### ISSUE THREAD

**Issue by yochannah** [open-life-science/open-life-science.github.io#268]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/9271438/108762066-8934d180-7547-11eb-933a-a8d4fbc2562a.png">

See screenshot - links in the OLS schedule page are missing the openlifesci.org part...

**Comment by bebatut** [comment]
Note for myself (to fix it): it is the link to weeks in OLS-3 syllabus page

**Comment by da5nsy** [comment]
Also in the links on the OLS2 schedule page

![image](https://user-images.githubusercontent.com/3739866/110414511-f2dfd000-805d-11eb-8291-e0429c883d92.png)

**Comment by emmyft** [comment]
I think this has been fixed? It works for me for both OLS-3 and 2

**Comment by da5nsy** [comment]
Still broken for me (Windows 10, Firefox 87.0 (64-bit))
On both the ols-2 and ols-3 pages the schedule links go to http://schedule/#week-XX
